apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 783764592295.dkr.ecr.ap-southeast-2.amazonaws.com/simplebank:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-server
        - containerPort: 9090
          name: grpc-server
        env:
        - name: DB_DSN
          value: "postgres://root:secret@172.18.0.2:5432/simple_bank"
        - name: REDIS_ADDR
          value: "redis://redis:6379"
        
